### ISSUE TITLE
R 3.3.0 Issues when Embedding

### ISSUE THREAD

**Issue by joshbode** [Homebrew/homebrew-science#3659]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?

`homebrew-science/r/3.3.0` is causing issues for `homebrew-science/r-gui/1.67` (also on latest version 1.68). Specifically, embedded instances of R 3.3.0 from homebrew-science cause R-GUI to exit on any parser error (missing object, syntax error, etc).  
This does not occur for either R 3.2.5 from homebrew-science or the official R 3.3.0 OS X binary from [CRAN](https://cran.r-project.org/bin/macosx/).

I have tracked it down to a difference in how `R_ReplDLLdo1()` returns on an error. In `homebrew-science/r/3.2.5` and the official 3.3.0 binary, the return is non-zero. However, in `homebrew-science/r/3.3.0`, the return is zero, which causes R-GUI to break its main loop. I've tried reinstalling and rebuilding 3.3.0 from source (ignoring bottle) but the effect is the same.

The following is the output of a minimal test ([gist](https://gist.github.com/joshbode/1e9600b78ecc4a6ef08fc7650cc73c24)) on embedding R using each version (where `/Library/Frameworks` denotes the official binary install):

```
/Library/Frameworks:
  1:
    output: [1] 1
    return: 1
  foo:
    output: Error: object 'foo' not found
    return: 208
  1 foo:
    output: Error: unexpected symbol in "1 foo"
    return: 208
  foo 1:
    output: Error: unexpected numeric constant in "foo 1"
    return: 208
  ):
    output: Error: unexpected ')' in ")"
    return: 208
  $:
    output: Error: unexpected '$' in "$"
    return: 208

/usr/local/Cellar/r/3.2.5:
  1:
    output: [1] 1
    return: 1
  foo:
    output: Error: object 'foo' not found
    return: 240
  1 foo:
    output: Error: unexpected symbol in "1 foo"
    return: 240
  foo 1:
    output: Error: unexpected numeric constant in "foo 1"
    return: 240
  ):
    output: Error: unexpected ')' in ")"
    return: 240
  $:
    output: Error: unexpected '$' in "$"
    return: 240

/usr/local/Cellar/r/3.3.0:
  1:
    output: [1] 1
    return: 1
  foo:
    output: Error: object 'foo' not found
    return: 0
  1 foo:
    output: Error: unexpected symbol in "1 foo"
    return: 0
  foo 1:
    output: Error: unexpected numeric constant in "foo 1"
    return: 0
  ):
    output: Error: unexpected ')' in ")"
    return: 0
  $:
    output: Error: unexpected '$' in "$"
    return: 0
```

Any thoughts on why this is returning zero in homebrew-science R 3.3.0 and not in other versions/binaries?
